---
- hosts: all
  become: yes
  tasks:
  - name: install openjdk 8
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tomcat7
    yum:
      name: tomcat7
    state: present
  - name: download jenkins to webapps folder
    get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.164.3/jenkins.war
      dest: /usr/share/tomcat7/webapps/jenkins.war
  - name: enable and start
    service:
      name: tomcat7
      state: started
      enabled: yes

